name: freeyaauerincatherine_bot_app_android
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/freeyaauerincatherine/freeyaauerincatherine_bot_app
repository: https://github.com/freeyaauerincatherine/freeyaauerincatherine_bot_app
issue_tracker: https://github.com/freeyaauerincatherine/freeyaauerincatherine_bot_app/issues 
documentation: https://youtube.com/@freeyaauerincatherine
funding:
  - https://github.com/sponsors/freeyaauerincatherine


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - freeyaauerincatherine_bot_app
#   - freeyaauerincatherine_bot_app_flutter
#   - freeyaauerincatherine_bot_app_dart

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
 